#!/usr/bin/env python3

import os
import sys
import pathlib
from romode.window import MainWindow

import gi
gi.require_version('Adw', '1')
from gi.repository import Adw


### The main part of the app
class MyApp(Adw.Application):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.connect('activate', self.on_activate)

    def on_activate(self, app):
        try:
            config_file = os.path.join(os.environ.get('HOME'), '.config/romode/config.json')
            if not os.path.exists(config_file):
                print("LOG: No config file found! Creating a new file at location: `" + config_file + "`\n")
                with open(config_file, 'w') as file:
                    pass
        
        except Exception as e:
            print("ERROR: Unable to create config file: ", e)
            return

        self.win = MainWindow(application=app, config_file=config_file)
        self.win.present()

app = MyApp()
app.run(sys.argv)