# borg-mount
# Autogenerated from man page /usr/share/man/man1/borg-mount.1.gz
complete -c borg-mount -l consider-checkpoints -d 'Show checkpoint archives in the repository contents list (default: hidden)'
complete -c borg-mount -s f -l foreground -d 'stay in foreground, do not daemonize'
complete -c borg-mount -s o -d 'Extra mount options'
complete -c borg-mount -l numeric-owner -d 'deprecated, use --numeric-ids instead'
complete -c borg-mount -l numeric-ids -d 'use numeric user and group identifiers from archive(s)'
complete -c borg-mount -s P -l prefix -d 'only consider archive names starting with this prefix.  (deprecated)'
complete -c borg-mount -s a -l glob-archives -d 'only consider archive names matching the glob'
complete -c borg-mount -l sort-by -d 'Comma-separated list of sorting keys; valid keys are: timestamp, archive, nam…'
complete -c borg-mount -l first -d 'consider first N archives after other filters were applied'
complete -c borg-mount -l last -d 'consider last N archives after other filters were applied'
complete -c borg-mount -s e -l exclude -d 'exclude paths matching PATTERN'
complete -c borg-mount -l exclude-from -d 'read exclude patterns from EXCLUDEFILE, one per line'
complete -c borg-mount -l pattern -d 'include/exclude paths matching PATTERN'
complete -c borg-mount -l patterns-from -d 'read include/exclude patterns from PATTERNFILE, one per line'
complete -c borg-mount -l strip-components -d 'Remove the specified number of leading path elements'

