# borg-serve
# Autogenerated from man page /usr/share/man/man1/borg-serve.1.gz
complete -c borg-serve -l restrict-to-path -d 'restrict repository access to PATH'
complete -c borg-serve -l restrict-to-repository -d 'restrict repository access'
complete -c borg-serve -l append-only -d 'only allow appending to repository segment files'
complete -c borg-serve -l storage-quota -d 'Override storage quota of the repository (e. g.  5G, 1. 5T)'
complete -c borg-serve -l lock-wait -d 'giving up and aborting the operation when another process is holding a lock'

