# borg-compact
# Autogenerated from man page /usr/share/man/man1/borg-compact.1.gz
complete -c borg-compact -l cleanup-commits -d 'cleanup commit-only 17-byte segment files'
complete -c borg-compact -l threshold -d 'set minimum threshold for saved space in PERCENT (Default: 10)'

