# borg-upgrade
# Autogenerated from man page /usr/share/man/man1/borg-upgrade.1.gz
complete -c borg-upgrade -s n -l dry-run -d 'do not change repository'
complete -c borg-upgrade -l inplace -d 'rewrite repository in place, with no chance of going back to older versions o…'
complete -c borg-upgrade -l force -d 'Force upgrade'
complete -c borg-upgrade -l tam -d 'Enable manifest authentication (in key and cache) (Borg 1. 0. 9 and later)'
complete -c borg-upgrade -l check-tam -d 'check manifest authentication (in key and cache)'
complete -c borg-upgrade -l disable-tam -d 'Disable manifest authentication (in key and cache)'
complete -c borg-upgrade -l check-archives-tam -d 'check TAM authentication for all archives'
complete -c borg-upgrade -l archives-tam -d 'add TAM authentication for all archives'

