# borg-diff
# Autogenerated from man page /usr/share/man/man1/borg-diff.1.gz
complete -c borg-diff -l numeric-owner -d 'deprecated, use --numeric-ids instead'
complete -c borg-diff -l numeric-ids -d 'only consider numeric user and group identifiers'
complete -c borg-diff -l same-chunker-params -d 'Override check of chunker parameters'
complete -c borg-diff -l sort -d 'Sort the output lines by file path'
complete -c borg-diff -l content-only -d 'Only compare differences in content (exclude metadata differences)'
complete -c borg-diff -l json-lines -d 'Format output as JSON Lines'
complete -c borg-diff -s e -l exclude -d 'exclude paths matching PATTERN'
complete -c borg-diff -l exclude-from -d 'read exclude patterns from EXCLUDEFILE, one per line'
complete -c borg-diff -l pattern -d 'include/exclude paths matching PATTERN'
complete -c borg-diff -l patterns-from -d 'read include/exclude patterns from PATTERNFILE, one per line'

