# borg-prune
# Autogenerated from man page /usr/share/man/man1/borg-prune.1.gz
complete -c borg-prune -s n -l dry-run -d 'do not change repository'
complete -c borg-prune -l force -d 'force pruning of corrupted archives, use --force --force in case --force does…'
complete -c borg-prune -s s -l stats -d 'print statistics for the deleted archive'
complete -c borg-prune -l list -d 'output verbose list of archives it keeps/prunes'
complete -c borg-prune -l keep-within -d 'keep all archives within this time interval'
complete -c borg-prune -l keep-last -l keep-secondly -d 'number of secondly archives to keep'
complete -c borg-prune -l keep-minutely -d 'number of minutely archives to keep'
complete -c borg-prune -s H -l keep-hourly -d 'number of hourly archives to keep'
complete -c borg-prune -s d -l keep-daily -d 'number of daily archives to keep'
complete -c borg-prune -s w -l keep-weekly -d 'number of weekly archives to keep'
complete -c borg-prune -s m -l keep-monthly -d 'number of monthly archives to keep'
complete -c borg-prune -s y -l keep-yearly -d 'number of yearly archives to keep'
complete -c borg-prune -l save-space -d 'work slower, but using less space'
complete -c borg-prune -s c -l checkpoint-interval -d 'write checkpoint every SECONDS seconds (Default: 1800)'
complete -c borg-prune -s P -l prefix -d 'only consider archive names starting with this prefix.  (deprecated)'
complete -c borg-prune -s a -l glob-archives -d 'only consider archive names matching the glob'

