# borg
# Autogenerated from man page /usr/share/man/man1/borg.1.gz
complete -c borg -l ---------------------------------------------------------------------------- -d 'Archive name: Tuesday Archive fingerprint: bd31004d58f51ea06ff735d2e5ac493769…'
complete -c borg -o rw-r--r-- -d ' 6'
complete -c borg -l verbose -l info -d 'get other informational messages'

