# borg-import-tar
# Autogenerated from man page /usr/share/man/man1/borg-import-tar.1.gz
complete -c borg-import-tar -l tar-filter -d 'filter program to pipe data through'
complete -c borg-import-tar -s s -l stats -d 'print statistics for the created archive'
complete -c borg-import-tar -l list -d 'output verbose list of items (files, dirs, . )'
complete -c borg-import-tar -l filter -d 'only display items with the given status characters'
complete -c borg-import-tar -l json -d 'output stats as JSON (implies --stats)'
complete -c borg-import-tar -l ignore-zeros -d 'ignore zero-filled blocks in the input tarball'
complete -c borg-import-tar -l comment -d 'add a comment text to the archive'
complete -c borg-import-tar -l timestamp -d 'manually specify the archive creation date/time (UTC, yyyy-mm-ddThh:mm:ss for…'
complete -c borg-import-tar -s c -l checkpoint-interval -d 'write checkpoint every SECONDS seconds (Default: 1800)'
complete -c borg-import-tar -l chunker-params -d 'specify the chunker parameters (ALGO, CHUNK_MIN_EXP, CHUNK_MAX_EXP, HASH_MASK…'
complete -c borg-import-tar -s C -l compression -d 'select compression algorithm, see the output of the "borg help compression" c…'

