# borg-config
# Autogenerated from man page /usr/share/man/man1/borg-config.1.gz
complete -c borg-config -s c -l cache -d 'get and set values from the repo cache'
complete -c borg-config -s d -l delete -d 'delete the key from the config file'
complete -c borg-config -s l -l list -d 'list the configuration of the repo'

