# borg-check
# Autogenerated from man page /usr/share/man/man1/borg-check.1.gz
complete -c borg-check -l repository-only -d 'only perform repository checks'
complete -c borg-check -l archives-only -d 'only perform archives checks'
complete -c borg-check -l verify-data -d 'perform cryptographic archive data integrity verification (conflicts with --r…'
complete -c borg-check -l repair -d 'attempt to repair any inconsistencies found'
complete -c borg-check -l save-space -d 'work slower, but using less space'
complete -c borg-check -l max-duration -d 'do only a partial repo check for max.  SECONDS seconds (Default: unlimited)'
complete -c borg-check -s P -l prefix -d 'only consider archive names starting with this prefix.  (deprecated)'
complete -c borg-check -s a -l glob-archives -d 'only consider archive names matching the glob'
complete -c borg-check -l sort-by -d 'Comma-separated list of sorting keys; valid keys are: timestamp, archive, nam…'
complete -c borg-check -l first -d 'consider first N archives after other filters were applied'
complete -c borg-check -l last -d 'consider last N archives after other filters were applied'

