# borg-patterns
# Autogenerated from man page /usr/share/man/man1/borg-patterns.1.gz
complete -c borg-patterns -l exclude-from -d 'The first matching pattern is used, so if an include pattern matches before a…'

