# borg-export-tar
# Autogenerated from man page /usr/share/man/man1/borg-export-tar.1.gz
complete -c borg-export-tar -l tar-filter -d 'filter program to pipe data through'
complete -c borg-export-tar -l list -d 'output verbose list of items (files, dirs, . )'
complete -c borg-export-tar -s e -l exclude -d 'exclude paths matching PATTERN'
complete -c borg-export-tar -l exclude-from -d 'read exclude patterns from EXCLUDEFILE, one per line'
complete -c borg-export-tar -l pattern -d 'include/exclude paths matching PATTERN'
complete -c borg-export-tar -l patterns-from -d 'read include/exclude patterns from PATTERNFILE, one per line'
complete -c borg-export-tar -l strip-components -d 'Remove the specified number of leading path elements'
complete -c borg-export-tar -l progress -d 'pass over the archive metadata.  OPTIONS'

