# borg-delete
# Autogenerated from man page /usr/share/man/man1/borg-delete.1.gz
complete -c borg-delete -s n -l dry-run -d 'do not change repository'
complete -c borg-delete -l list -d 'output verbose list of archives'
complete -c borg-delete -s s -l stats -d 'print statistics for the deleted archive'
complete -c borg-delete -l cache-only -d 'delete only the local cache for the given repository'
complete -c borg-delete -l force -d 'force deletion of corrupted archives, use --force --force in case --force doe…'
complete -c borg-delete -l keep-security-info -d 'keep the local security info when deleting a repository'
complete -c borg-delete -l save-space -d 'work slower, but using less space'
complete -c borg-delete -s c -l checkpoint-interval -d 'write checkpoint every SECONDS seconds (Default: 1800)'
complete -c borg-delete -s P -l prefix -d 'only consider archive names starting with this prefix.  (deprecated)'
complete -c borg-delete -s a -l glob-archives -d 'only consider archive names matching the glob'
complete -c borg-delete -l sort-by -d 'Comma-separated list of sorting keys; valid keys are: timestamp, archive, nam…'
complete -c borg-delete -l first -d 'consider first N archives after other filters were applied'
complete -c borg-delete -l last -d 'consider last N archives after other filters were applied'

