# borg-init
# Autogenerated from man page /usr/share/man/man1/borg-init.1.gz
complete -c borg-init -s e -l encryption -d 'select encryption key mode (required)'
complete -c borg-init -l append-only -d 'create an append-only mode repository'
complete -c borg-init -l storage-quota -d 'Set storage quota of the new repository (e. g.  5G, 1. 5T)'
complete -c borg-init -l make-parent-dirs -d 'create the parent directories of the repository directory, if they are missing'

