# borg-key-export
# Autogenerated from man page /usr/share/man/man1/borg-key-export.1.gz
complete -c borg-key-export -l paper -d 'Create an export suitable for printing and later type-in'
complete -c borg-key-export -l qr-html -d 'Create an html file suitable for printing and later type-in or qr scan'

