# borg-list
# Autogenerated from man page /usr/share/man/man1/borg-list.1.gz
complete -c borg-list -l consider-checkpoints -d 'Show checkpoint archives in the repository contents list (default: hidden)'
complete -c borg-list -l short -d 'only print file/directory names, nothing else'
complete -c borg-list -l format -d 'specify format for file or archive listing (default for files: "{mode} {user:…'
complete -c borg-list -l json -d 'Only valid for listing repository contents.  Format output as JSON'
complete -c borg-list -l json-lines -d 'Only valid for listing archive contents.  Format output as JSON Lines'
complete -c borg-list -s P -l prefix -d 'only consider archive names starting with this prefix.  (deprecated)'
complete -c borg-list -s a -l glob-archives -d 'only consider archive names matching the glob'
complete -c borg-list -l sort-by -d 'Comma-separated list of sorting keys; valid keys are: timestamp, archive, nam…'
complete -c borg-list -l first -d 'consider first N archives after other filters were applied'
complete -c borg-list -l last -d 'consider last N archives after other filters were applied'
complete -c borg-list -s e -l exclude -d 'exclude paths matching PATTERN'
complete -c borg-list -l exclude-from -d 'read exclude patterns from EXCLUDEFILE, one per line'
complete -c borg-list -l pattern -d 'include/exclude paths matching PATTERN'
complete -c borg-list -l patterns-from -d 'read include/exclude patterns from PATTERNFILE, one per line'
complete -c borg-list -o rwxr-xr-x -d 'lrwxrwxrwx root   root          0 Fri, 2015-03-27 20:24:26 bin/bzcmp -> bzdiff'
complete -c borg-list -o rw-rw-r--

