# borg-info
# Autogenerated from man page /usr/share/man/man1/borg-info.1.gz
complete -c borg-info -l json -d 'format output as JSON'
complete -c borg-info -s P -l prefix -d 'only consider archive names starting with this prefix.  (deprecated)'
complete -c borg-info -s a -l glob-archives -d 'only consider archive names matching the glob'
complete -c borg-info -l sort-by -d 'Comma-separated list of sorting keys; valid keys are: timestamp, archive, nam…'
complete -c borg-info -l first -d 'consider first N archives after other filters were applied'
complete -c borg-info -l last -d 'consider last N archives after other filters were applied'
complete -c borg-info -l ---------------------------------------------------------------------------- -d '                       Original size      Compressed size    Deduplicated siz…'

