# borg-extract
# Autogenerated from man page /usr/share/man/man1/borg-extract.1.gz
complete -c borg-extract -l list -d 'output verbose list of items (files, dirs, . )'
complete -c borg-extract -s n -l dry-run -d 'do not actually change any files'
complete -c borg-extract -l numeric-owner -d 'deprecated, use --numeric-ids instead'
complete -c borg-extract -l numeric-ids -d 'only obey numeric user and group identifiers'
complete -c borg-extract -l nobsdflags -d 'deprecated, use --noflags instead'
complete -c borg-extract -l noflags -d 'do not extract/set flags (e. g.  NODUMP, IMMUTABLE)'
complete -c borg-extract -l noacls -d 'do not extract/set ACLs'
complete -c borg-extract -l noxattrs -d 'do not extract/set xattrs'
complete -c borg-extract -l stdout -d 'write all extracted data to stdout'
complete -c borg-extract -l sparse -d 'create holes in output sparse file from all-zero chunks'
complete -c borg-extract -s e -l exclude -d 'exclude paths matching PATTERN'
complete -c borg-extract -l exclude-from -d 'read exclude patterns from EXCLUDEFILE, one per line'
complete -c borg-extract -l pattern -d 'include/exclude paths matching PATTERN'
complete -c borg-extract -l patterns-from -d 'read include/exclude patterns from PATTERNFILE, one per line'
complete -c borg-extract -l strip-components -d 'Remove the specified number of leading path elements'
complete -c borg-extract -l progress -d 'pass over the archive metadata'

