# checkupdates
# Autogenerated from man page /usr/share/man/man8/checkupdates.8.gz
complete -c checkupdates -s c -l change -d 'Check for new available updates only, prints the list of available updates on…'
complete -c checkupdates -s d -l download -d 'Download any pending updates to the pacman cache'
complete -c checkupdates -s h -l help -d 'Display syntax and command-line options'
complete -c checkupdates -l nocolor -d 'Do not colorize output.  Color must be enabled in pacman'
complete -c checkupdates -s n -l nosync -d 'Do not sync the temporary database, works best when the temporary database is…'
complete -c checkupdates -s V -l version -d 'Display version information'

