# dunst
# Autogenerated from man page /usr/share/man/man1/dunst.1.gz
complete -c dunst -o h/-help/--help
complete -c dunst -o conf/-config
complete -c dunst -o v/-version/--version
complete -c dunst -o verbosity
complete -c dunst -o print/--print
complete -c dunst -o startup_notification/--startup_notification

