# hyprpicker
# Autogenerated from man page /usr/share/man/man1/hyprpicker.1.gz
complete -c hyprpicker -s a -d 'Automatically copy the output of hyprpicker to the clipboard'
complete -c hyprpicker -s f -d 'Select the format to output the selected pixels color in'
complete -c hyprpicker -s n -d 'Disable colored output'
complete -c hyprpicker -s h -d 'Display a help message and exit successfully from the program'

