# iscsi-md5sum
# Autogenerated from man page /usr/share/man/man1/iscsi-md5sum.1.gz
complete -c iscsi-md5sum -s i -l initiator-name -d 'This specifies the initiator-name that iscsi-md5sum will use when logging in …'
complete -c iscsi-md5sum -s o -l offset -d 'Byte offset into the target from which to start calculating'
complete -c iscsi-md5sum -s l -l length -d 'The number of bytes to calculate (counting from the starting point)'
complete -c iscsi-md5sum -s d -l debug -d 'Print debug information'
complete -c iscsi-md5sum -s '?' -l help -d 'Display basic help text'
complete -c iscsi-md5sum -l usage -d 'Display basic usage text'

