# libnet-config
# Autogenerated from man page /usr/share/man/man1/libnet-config.1.gz
complete -c libnet-config -l cflags -d 'Set of compiler options (CFLAGS) to use when compiling files that use libnet'
complete -c libnet-config -l libs -d 'Shows the complete set of libs and other linker options you will need in orde…'
complete -c libnet-config -l defines -d 'Set of compiler defines used to compile libnet'

