# mkvextract
# Autogenerated from man page /usr/share/man/man1/mkvextract.1.gz
complete -c mkvextract -s f -l parse-fully
complete -c mkvextract -l command-line-charset
complete -c mkvextract -l output-charset
complete -c mkvextract -s r -l redirect-output
complete -c mkvextract -l flush-on-close
complete -c mkvextract -l ui-language
complete -c mkvextract -l abort-on-warnings
complete -c mkvextract -l debug
complete -c mkvextract -l engage
complete -c mkvextract -l gui-mode
complete -c mkvextract -s v -l verbose
complete -c mkvextract -s h -l help
complete -c mkvextract -s V -l version
complete -c mkvextract -s c
complete -c mkvextract -l blockadd
complete -c mkvextract -l cuesheet
complete -c mkvextract -l raw
complete -c mkvextract -l fullraw -d 'flag this flag does not cause the contents of the CodecPrivate element to be …'
complete -c mkvextract -l identify -d option
complete -c mkvextract -s s -l simple
complete -c mkvextract -l simple-language

