# mkvinfo
# Autogenerated from man page /usr/share/man/man1/mkvinfo.1.gz
complete -c mkvinfo -s a -l all
complete -c mkvinfo -s c -l checksums
complete -c mkvinfo -s o -l continue
complete -c mkvinfo -s p -l hex-positions
complete -c mkvinfo -s P -l positions
complete -c mkvinfo -s s -l summary
complete -c mkvinfo -s t -l track-info
complete -c mkvinfo -s x -l hexdump
complete -c mkvinfo -s X -l full-hexdump
complete -c mkvinfo -s z -l size
complete -c mkvinfo -l command-line-charset
complete -c mkvinfo -l output-charset
complete -c mkvinfo -s r -l redirect-output
complete -c mkvinfo -l ui-language
complete -c mkvinfo -l abort-on-warnings
complete -c mkvinfo -l debug
complete -c mkvinfo -l engage
complete -c mkvinfo -l gui-mode
complete -c mkvinfo -s v -l verbose
complete -c mkvinfo -s h -l help
complete -c mkvinfo -s V -l version

