# mkvpropedit
# Autogenerated from man page /usr/share/man/man1/mkvpropedit.1.gz
complete -c mkvpropedit -s l -l list-property-names
complete -c mkvpropedit -s p -l parse-mode
complete -c mkvpropedit -s e -l edit
complete -c mkvpropedit -s a -l add
complete -c mkvpropedit -s s -l set
complete -c mkvpropedit -s d -l delete
complete -c mkvpropedit -s t -l tags
complete -c mkvpropedit -l add-track-statistics-tags
complete -c mkvpropedit -l delete-track-statistics-tags
complete -c mkvpropedit -s c -l chapters
complete -c mkvpropedit -l add-attachment
complete -c mkvpropedit -l attachment-name -d 'has been used prior to this option then its value is used as the new attachme…'
complete -c mkvpropedit -l attachment-mime-type -d 'has been used prior to this option then its value is used as the new attachme…'
complete -c mkvpropedit -l attachment-description -d 'has been used prior to this option then its value is used as the new attachme…'
complete -c mkvpropedit -l attachment-uid -d 'has been used prior to this option then its value is used as the new attachme…'
complete -c mkvpropedit -l replace-attachment
complete -c mkvpropedit -l update-attachment
complete -c mkvpropedit -l delete-attachment
complete -c mkvpropedit -l enable-legacy-font-mime-types
complete -c mkvpropedit -l disable-language-ietf
complete -c mkvpropedit -l normalize-language-ietf
complete -c mkvpropedit -l command-line-charset
complete -c mkvpropedit -l output-charset
complete -c mkvpropedit -s r -l redirect-output
complete -c mkvpropedit -l ui-language
complete -c mkvpropedit -l abort-on-warnings
complete -c mkvpropedit -l debug
complete -c mkvpropedit -l engage
complete -c mkvpropedit -l gui-mode
complete -c mkvpropedit -s v -l verbose
complete -c mkvpropedit -s h -l help
complete -c mkvpropedit -s V -l version
complete -c mkvpropedit -l identify -d 'option outputs'

