# sshfs
# Autogenerated from man page /usr/share/man/man1/sshfs.1.gz
complete -c sshfs -s o -d 'mount options, see below for details'
complete -c sshfs -s h -l help -d 'print help and exit'
complete -c sshfs -s V -l version -d 'print version information and exit'
complete -c sshfs -s d -l debug -d 'print debugging information'
complete -c sshfs -s p -d 'equivalent to \'-o port=PORT\''
complete -c sshfs -s f -d 'do not daemonize, stay in foreground'
complete -c sshfs -s s -d 'Single threaded operation'
complete -c sshfs -s C -d 'equivalent to \'-o compression=yes\''
complete -c sshfs -s F -d 'specifies alternative ssh configuration file'
complete -c sshfs -s 1 -d 'equivalent to \'-o ssh_protocol=1\''

