# swappy
# Autogenerated from man page /usr/share/man/man1/swappy.1.gz
complete -c swappy -s h -l help -d 'Show help message and quit'
complete -c swappy -s v -l version -d 'Show version and quit'
complete -c swappy -s f -l file -d 'An image file to load for editing'
complete -c swappy -s o -l output-file -d 'Print the final surface to <file> when exiting the application'

