# wev
# Autogenerated from man page /usr/share/man/man1/wev.1.gz
complete -c wev -s g -d 'Print globals'
complete -c wev -s f -d 'Only show events for the given Wayland interface, or for a specific event'
complete -c wev -s F -d 'Show all events except those from the given Wayland interface, or except'
complete -c wev -s M -d 'Writes the wl_keyboard\'s keymap to the specified path'

