# wlogout
# Autogenerated from man page /usr/share/man/man1/wlogout.1.gz
complete -c wlogout -s l -l layout -d 'Specify a custom layout file'
complete -c wlogout -s v -l version -d 'Show version number and stop'
complete -c wlogout -s C -o css -d 'Specify a custom css file'
complete -c wlogout -s b -l buttons-per-row -d 'Set the number of buttons per row'
complete -c wlogout -s c -l column-spacing -d 'Set space between buttons columns'
complete -c wlogout -s r -l row-spacing -d 'Set space between buttons rows'
complete -c wlogout -s m -l margin -d 'Set margin on all sides'
complete -c wlogout -s L -l margin-left -d 'Set margin for left of buttons'
complete -c wlogout -s R -l margin-right -d 'Set margin for right of buttons'
complete -c wlogout -s T -d 'Set margin for top of buttons'
complete -c wlogout -s B -d 'Set margin for bottom of buttons'
complete -c wlogout -s p -l protocol -d 'Takes either layer-shell or xdg'
complete -c wlogout -s s -l show-binds -d 'Will show the keybinds of a button by inserting the key needed to activate th…'
complete -c wlogout -s P -l primary-monitor -d 'Select the monitor to display buttons on; Monitors are numbered from 0 up'
complete -c wlogout -s n -l no-span -d 'Stops wlogout from spanning across multiple monitors, can be combined with `-…'

